version: '3'
services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: ./docker/elixir/Dockerfile
        image: phoenixfeeds:latest
        restart: always
        ports:
            - "4000:4000"
        volumes:
            - "./app/phxfeeds:/phxfeeds"
